name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.GCLOUD_KEY }}
        run: |
          TAG=$GITHUB_REF
          TAG=${TAG#refs/tags/}
          DOCKER_IMAGE=${DOCKER_USERNAME}/Dockerfile

          docker buildx create --use
          docker buildx build --push --platform linux/amd64,linux/arm64 -t $DOCKER_IMAGE:$TAG .
          echo "${DOCKER_TOKEN}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          docker push $DOCKER_IMAGE:$TAG
