name: Docker Semver Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        DOCKER_TAG=$(echo "${GITHUB_REF}" | cut -d "/" -f 3)
        docker build . --file Dockerfile --tag my-image-name:${DOCKER_TAG}
        docker push my-image-name:${DOCKER_TAG}
