name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

env:
  TAGGED_VERSION: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tagged version
        if: |
          startsWith(github.event_name, 'push') && startsWith(github.ref, 'refs/tags/v')
        run: |
          TAGGED_VERSION=$(echo "${{ github.ref }}" | sed -e 's|^refs/tags/v||')

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        if: ${{ env.TAGGED_VERSION }}
        run: |
          docker build -t dzburst/ci-cd_project:${TAGGED_VERSION} .
          docker images
          docker push dzburst/ci-cd_project:${TAGGED_VERSION}

      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Set up Cloud Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCLOUD_KEY }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: esirem

      - name: Configure Docker using GCLOUD
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.3.1
        with:
          # Emplacement du Dockerfile
          file: Dockerfile
          tags: europe-west1-docker.pkg.dev/esirem/esirem/4a_ilc/hadji_mouazer/ci-cd_project:${{ github.ref_name }}

          # Emplacement des fichiers 
          context: .
          push: true
