name: Build and Push Docker Image

on:
  push:
    branches: 
      ["main"]
    tags:
      - 'v*.*.*'  

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        TAG=$GITHUB_REF
        TAG=${TAG#refs/tags/}  # Retirer le préfixe refs/tags/ du tag

        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t docker_image.yml:$TAG .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push docker_image.yml:$TAG
