name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          TAGGED_VERSION: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.event.head_commit ? github.event.head_commit.message | regex_replace('v', '') : '' }}
        run: |
          docker build -t dzburst/ci-cd_project:${TAGGED_VERSION} .
          docker push dzburst/ci-cd_project:${TAGGED_VERSION}
